---
namespace: miteshget

name: eda
version: 0.0.1

authors:
  - Mitesh The Mouse
description: Ansible Event Driven Automation


tags:
  - k8s
  - eda

readme: README.md
dependencies: {}


build_ignore: []
